version: '2'

services:
  redis:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - 6379:6379
  mq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
