name: Upload Images

on:
  push:
    branches:
      - main

jobs:
  upload-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload image 1
        uses: actions/upload-artifact@v2
        with:
          name: exchange
          path: .github/exchange.png
      - name: Upload image 2
        uses: actions/upload-artifact@v2
        with:
          name: queue
          path: .github/queue.png
